name: version bump

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node: ['internal.yml', 'external.yml', 'datascience.yml']

    steps:
      - uses: actions/checkout@v2
      
      - name: Update Version on Yaml File
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: ${{ matrix.node }}
          propertyPath: info.version
          value: 4.0.0
          commitChange: true
          updateFile: true
          targetBranch: master
          masterBranchName: master
          createPR: false
          branch:  master
          message: Bump version to 4.0.0 in ${{ matrix.node }}


