name: version bump

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node: [['internal.yml', 6.0.0], ['external.yml', 6.0.0], ['datascience.yml', 6.0.0]]

    steps:
      - uses: actions/checkout@v2
      
      - name: Update Version on Yaml File
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: ${{ matrix.node[0] }}
          propertyPath: info.version
          value: ${{ matrix.node[1] }}
          commitChange: true
          updateFile: true
          targetBranch: master
          masterBranchName: master
          createPR: false
          branch:  master
          message: Bump version to  ${{ matrix.node[1] }} in ${{ matrix.node[0] }}


