name: version bump

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            file: ['internal.yml', 'external.yml', 'datascience.yml']
            value: [5.0.0, 5.0.0, 5.0.0]

    steps:
      - uses: actions/checkout@v2
      
      - name: Update Version on Yaml File
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: ${{ matrix.file }}
          propertyPath: info.version
          value: ${{ matrix.value }}
          commitChange: true
          updateFile: true
          targetBranch: master
          masterBranchName: master
          createPR: false
          branch:  master
          message: Bump version to  ${{ matrix.value }} in ${{ matrix.file }}


